// Generated from SipWebPhoneProviders.json. Do not edit this file directly.
(function (root) {
  root.FritzSipProviderTable = {
    "schemaVersion": "1",
    "providers": {
      "sipgate": {
        "name": "Sipgate",
        "websocket": "wss://sip.sipgate.de:443",
        "credentialsMode": "sip-account",
        "documentation": "https://help.sipgate.de/hc/de/articles/4983838712477-Was-sind-die-IP-und-Port-Bereiche-von-sipgate",
        "verifiedAt": "2026-08-08"
      }
    },
    "registrars": {
      "sipgate.de": "sipgate",
      "sip.sipgate.de": "sipgate"
    }
  };
})(typeof globalThis !== "undefined" ? globalThis : this);
